# ===============================
# PUERTO DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURACION BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_pedidos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACION JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Opcional - Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 DESACTIVADO
# ===============================
spring.h2.console.enabled=false